spring.application.name=bookstore-api

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Web server
server.port=8081

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000