spring.application.name=bookstore-api

# PostgreSQL bağlantısı
spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Web sunucusu
server.port=8081

# Admin info
app.admin.email=${ADMIN_EMAIL:}
app.admin.password=${ADMIN_PASSWORD:}
app.admin.first-name=${ADMIN_FIRST_NAME:Admin}
app.admin.last-name=${ADMIN_LAST_NAME:User}